version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: template
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
  ui:
      image: mobin79/webproject
      depends_on:
        - postgres
      volumes:
        -
          type: bind
          source: ./template.json
          target: /app/template.json
      ports:
        - "10022:8081"
volumes:
  postgres:
