version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: template
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis-cache:
    image: redis
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
  postgres: